export type Group =
  | "Structure"
  | "Propulsion"
  | "Avionics"
  | "Perception"
  | "Navigation"
  | "Power"
  | "Link"
  | "Ground";

export type Tier = "airframe" | "fly" | "fsd" | "ground";

export type Origin = "buy" | "print" | "machine" | "included";

export type Spec = { label: string; value: string };

export type BomItem = {
  id: string;
  catalogId: string | null;
  name: string;
  sku: string;
  brand: string;
  group: Group;
  tier: Tier;
  qty: number;
  unitUsd: number;
  match: string;
  why: string;
  specs: Spec[];
  buyUrl: string;
  vendor: string;
  image: string | null;
  note?: string;
  included?: boolean;
  origin?: Origin;
  cadId?: string;
  process?: string;
  materialName?: string;
};

export const GROUPS: Group[] = [
  "Structure",
  "Propulsion",
  "Avionics",
  "Perception",
  "Navigation",
  "Power",
  "Link",
  "Ground",
];

export const TIERS: { id: Tier; label: string; hint: string }[] = [
  { id: "airframe", label: "Airframe", hint: "Spins on the bench" },
  { id: "fly", label: "Flyable", hint: "PX4 + radio + pack" },
  { id: "fsd", label: "Vision FSD", hint: "Orin + camera lock" },
  { id: "ground", label: "Ground", hint: "Charge, tools, spares" },
];

export const AIRFRAME = {
  name: "HV-1 OSPREY",
  program: "Horizon Vision",
  source: "hrishileo/Vision-Quest",
  layout: "X · 650 mm",
  auw: "1.85 kg target",
  pack: "6S 6 000 mAh",
  hover: "18 A",
  endurance: "14 min chase",
};

export const ITEMS: BomItem[] = [
  {
    id: "frame",
    catalogId: "frame",
    name: "HV-1 OSPREY carbon chassis",
    sku: "HV-1-FRM-00  ·  REV B",
    brand: "Horizon Vision",
    group: "Structure",
    tier: "airframe",
    qty: 1,
    unitUsd: 340,
    match: "X · 650 mm · osprey 3K plates · 24×10 box arms · 19×19 bulkheads",
    why: "Custom Creo/AutoCAD chassis. Same 650 mm true-X and 19 × 19 motor pattern as the X650 donor so the 3115s, Pixhawk Mini, Orin tray and Tattu pack drop in. Machine the plates; do not buy the X650 ARF (wrong motors).",
    specs: [
      { label: "Wheelbase", value: "650 mm" },
      { label: "Plates", value: "152 × 218 × 2.5 mm 3K" },
      { label: "Arms", value: "24 × 10 mm CF box" },
    ],
    buyUrl: "",
    vendor: "Machine in-house",
    image: "/bom/frame.jpg",
    origin: "machine",
    cadId: "frm-00",
    process: "CNC 3K + 6061 bulkheads",
    materialName: "3K twill 2.5 mm · 6061-T6",
    note: "AUW target in the briefing is 1.85 kg. A first article with Orin + 6S 6000 will land closer to 2.3–2.8 kg. Keep the payload plate empty on the first flights.",
  },
  {
    id: "motors",
    catalogId: "motors",
    name: "3115-class outrunners, 900 Kv",
    sku: "Hobbywing XRotor 3115 900KV",
    brand: "Hobbywing",
    group: "Propulsion",
    tier: "airframe",
    qty: 4,
    unitUsd: 36,
    match: "31 × 15 mm stator · 900 Kv · ~1.6 kgf / axis on 10×5.5",
    why: "Catalog motors are 3115 / 900 Kv. Same can as the XRotor 3115 (photo is the 1050 Kv sibling). Order the 900 Kv winding for 6S / 10-inch two-blade.",
    specs: [
      { label: "Kv", value: "900" },
      { label: "Stator", value: "31 × 15 mm" },
      { label: "Mount", value: "19 × 19 · M3 · M5 shaft" },
    ],
    buyUrl: "https://www.hobbywing.com/en/products/xrotor3115",
    vendor: "Hobbywing",
    image: "/bom/motor.jpg",
  },
  {
    id: "props",
    catalogId: "props",
    name: "10-inch carbon two-blade",
    sku: "HQProp / Gemfan 10×5.5×2 CF  (CW + CCW)",
    brand: "HQProp",
    group: "Propulsion",
    tier: "airframe",
    qty: 2,
    unitUsd: 18,
    match: "10 in · 5.5 in pitch · CW · CCW · CW · CCW",
    why: "Two pairs = four blades, opposite rotation on opposite arms. Carbon holds pitch under chase load better than nylon.",
    specs: [
      { label: "Size", value: "10 × 5.5 × 2" },
      { label: "Pairing", value: "2 CW + 2 CCW" },
      { label: "Hub", value: "M5" },
    ],
    buyUrl: "https://www.hqprop.com/",
    vendor: "HQProp / GetFPV",
    image: "/bom/props.jpg",
    note: "Qty 2 means two pairs (four props). Buy a second set as spares in Ground.",
  },
  {
    id: "escs",
    catalogId: "escs",
    name: "4-in-1 ESC, 45 A",
    sku: "Hobbywing XRotor 45A 4-in-1  3–6S",
    brand: "Hobbywing",
    group: "Propulsion",
    tier: "airframe",
    qty: 1,
    unitUsd: 90,
    match: "DShot600 · 45 A cont. / motor · eRPM · A · °C telemetry",
    why: "Catalog mixer is DShot600 at 45 A continuous. Hover is ~18 A pack, so 45 A has headroom. If you later move to 10-inch tri-blades, step up to a 60–80 A 4-in-1.",
    specs: [
      { label: "Protocol", value: "DShot600" },
      { label: "Current", value: "45 A × 4" },
      { label: "Input", value: "3–6S" },
    ],
    buyUrl: "https://www.hobbywing.com/en/products/xrotor-fpv-g2-45a-4in1-esc",
    vendor: "Hobbywing",
    image: "/bom/esc.jpg",
  },
  {
    id: "fc",
    catalogId: "fc",
    name: "Flight controller",
    sku: "Holybro Pixhawk 6C Mini + PM02",
    brand: "Holybro",
    group: "Avionics",
    tier: "fly",
    qty: 1,
    unitUsd: 150,
    match: "STM32H743 · BMI088 · PX4 1.15",
    why: "Exact MCU and gyro from the briefing. Mini form fits the 160 mm plates. PM02 is the 6S-safe power module the 6C needs. Flash PX4 1.15, not Betaflight — companion setpoints arrive as NED, not RC overrides.",
    specs: [
      { label: "MCU", value: "STM32H743" },
      { label: "Gyro", value: "BMI088 + ICM-42688-P" },
      { label: "Firmware", value: "PX4 1.15" },
    ],
    buyUrl: "https://holybro.com/products/pixhawk-6c-mini",
    vendor: "Holybro",
    image: "/bom/avionics.jpg",
    note: "Holybro also sells a Pixhawk + Jetson carrier. Skip it for HV-1: that board wants Orin NX, not the Nano 8 GB the catalog specifies.",
  },
  {
    id: "imu",
    catalogId: "imu",
    name: "IMU · gyro + accel",
    sku: "BMI088  (on Pixhawk 6C Mini)",
    brand: "Bosch / Holybro",
    group: "Avionics",
    tier: "fly",
    qty: 1,
    unitUsd: 0,
    match: "±2000 °/s · ±24 g · 4 kHz",
    why: "Not a separate buy. The 6C Mini carries a BMI088 as the primary IMU — same part the exploded model labels. Do not add a second external IMU unless you are doing research-grade vibration isolation.",
    specs: [
      { label: "Gyro", value: "±2000 °/s" },
      { label: "Accel", value: "±24 g" },
      { label: "Rate", value: "4 kHz" },
    ],
    buyUrl: "https://holybro.com/products/pixhawk-6c-mini",
    vendor: "Included",
    image: "/bom/avionics.jpg",
    included: true,
  },
  {
    id: "npu",
    catalogId: "npu",
    name: "Jetson Orin Nano 8 GB",
    sku: "NVIDIA Jetson Orin Nano Super Developer Kit",
    brand: "NVIDIA",
    group: "Perception",
    tier: "fsd",
    qty: 1,
    unitUsd: 399,
    match: "Orin Nano 8 GB · 40 TOPS INT8 (67 TOPS Super) · CSI + UART",
    why: "This is the FSD computer. Buy the Super kit so you have a supported JetPack box. Fly the module on a compact carrier — the desktop board + fan is too heavy for the 1.85 kg AUW target.",
    specs: [
      { label: "Module", value: "Orin Nano 8 GB" },
      { label: "Compute", value: "40–67 TOPS" },
      { label: "Link", value: "CSI + 50 Hz UART" },
    ],
    buyUrl:
      "https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-orin/nano-super-developer-kit/",
    vendor: "NVIDIA / Amazon",
    image: "/bom/orin.jpg",
    note: "Street price jumped from $249 to $399 in 2026. For the airframe, add a compact carrier (Seeed / Waveshare, ~$70) and a 2230 NVMe. Do not bolt the full Dev Kit to the top plate.",
  },
  {
    id: "carrier",
    catalogId: "npu",
    name: "Compact Orin carrier",
    sku: "Seeed / Waveshare Orin Nano carrier (J401 class)",
    brand: "Seeed",
    group: "Perception",
    tier: "fsd",
    qty: 1,
    unitUsd: 79,
    match: "CSI + USB-C + UART · flight-weight vs desktop kit",
    why: "The Super kit is for the bench. The flight article needs the 8 GB module on a small carrier so camera_link stays rigid to the IMU.",
    specs: [
      { label: "CSI", value: "2× MIPI" },
      { label: "Power", value: "9–19 V" },
      { label: "Mass", value: "~60 g board" },
    ],
    buyUrl: "https://www.seeedstudio.com/reComputer-J4012-optional-accessories.html",
    vendor: "Seeed / Waveshare",
    image: "/bom/orin.jpg",
  },
  {
    id: "ssd",
    catalogId: "npu",
    name: "NVMe 256 GB (2230)",
    sku: "WD SN530 / SN740 256 GB 2230",
    brand: "Western Digital",
    group: "Perception",
    tier: "fsd",
    qty: 1,
    unitUsd: 35,
    match: "JetPack + detector weights + logs",
    why: "Orin will not boot a useful stack from eMMC on the Nano. A 2230 NVMe is the standard Super-kit boot drive.",
    specs: [
      { label: "Form", value: "M.2 2230" },
      { label: "Size", value: "256 GB" },
      { label: "Bus", value: "NVMe" },
    ],
    buyUrl: "https://www.amazon.com/s?k=2230+nvme+256gb",
    vendor: "Amazon",
    image: null,
  },
  {
    id: "camera",
    catalogId: "camera",
    name: "Vision FSD camera",
    sku: "Arducam B0429 AR0234  (or IMX296) CSI global shutter",
    brand: "Arducam",
    group: "Perception",
    tier: "fsd",
    qty: 1,
    unitUsd: 99,
    match: "CSI · global shutter · 1280×720 · 30–60 fps · ~70° HFOV",
    why: "Horizon Vision dropped LiDAR. Range is pinhole + AGL, so the camera must be global shutter or a 15 m/s chase shears the box. Fit a ~70° M12 lens. Rolling-shutter IMX219 is the wrong part.",
    specs: [
      { label: "Interface", value: "MIPI CSI-2" },
      { label: "Shutter", value: "Global" },
      { label: "HFOV", value: "70° class" },
    ],
    buyUrl: "https://www.arducam.com/",
    vendor: "Arducam",
    image: "/bom/camera.jpg",
  },
  {
    id: "gimbal",
    catalogId: "gimbal",
    name: "Two-axis gimbal",
    sku: "Tarot T-2D / SimpleBGC Mini 2-axis",
    brand: "Tarot / BaseCam",
    group: "Perception",
    tier: "fsd",
    qty: 1,
    unitUsd: 119,
    match: "Yaw + pitch · ±110° / −90…+30° · pixel closed-loop",
    why: "Keeps the target near the optical centre so the detector is not fighting airframe pitch. Pick a 2-axis (not 3-axis cine) sized for a ~30 g CSI module.",
    specs: [
      { label: "Axes", value: "Yaw + pitch" },
      { label: "Travel", value: "±110° / −90…+30°" },
      { label: "Follow", value: "Pixel closed-loop" },
    ],
    buyUrl: "https://www.tarotrc.com/",
    vendor: "Tarot / GetFPV",
    image: "/bom/gimbal.jpg",
  },
  {
    id: "gps",
    catalogId: "gps",
    name: "GNSS + compass mast",
    sku: "Holybro H-RTK NEO-F9P helical + RM3100",
    brand: "Holybro",
    group: "Navigation",
    tier: "fly",
    qty: 1,
    unitUsd: 249,
    match: "L1 / L2 (L1+L5) · ~1.2–1.5 m CEP · 10 Hz · RM3100 mag",
    why: "Dual-band puck on an 80 mm mast, out of the ESC current loop. PVT CEP matches the briefing; RTK is extra. This one SKU covers both the GPS and the RM3100 magnetometer in the exploded model.",
    specs: [
      { label: "Bands", value: "L1 / L2 / L5" },
      { label: "CEP", value: "1.5 m PVT · 1.2 m SBAS" },
      { label: "Mag", value: "RM3100" },
    ],
    buyUrl: "https://holybro.com/products/dronecan-h-rtk-f9p-rover",
    vendor: "Holybro",
    image: "/bom/gps.jpg",
    note: "Classic H-RTK F9P Helical (~$219) uses an IST8310. If you buy that one, add a standalone Holybro RM3100 ($45) to match the catalog mag.",
  },
  {
    id: "mag",
    catalogId: "mag",
    name: "Magnetometer",
    sku: "PNI RM3100  (on NEO-F9P mast)",
    brand: "PNI / Holybro",
    group: "Navigation",
    tier: "fly",
    qty: 1,
    unitUsd: 0,
    match: "RM3100 · 100 Hz · mast 80 mm",
    why: "Included with the NEO-F9P SKU above. Heading lock in hover; during a chase, yaw is optical, mag is a bias prior.",
    specs: [
      { label: "Sensor", value: "RM3100" },
      { label: "Rate", value: "100 Hz" },
      { label: "Mount", value: "Mast, 80 mm" },
    ],
    buyUrl: "https://holybro.com/products/dronecan-h-rtk-f9p-rover",
    vendor: "Included",
    image: "/bom/gps.jpg",
    included: true,
  },
  {
    id: "battery",
    catalogId: "battery",
    name: "6S LiPo pack",
    sku: "Tattu 22.2 V 6000 mAh 25C 6S · XT90",
    brand: "Tattu / Gens Ace",
    group: "Power",
    tier: "fly",
    qty: 2,
    unitUsd: 95,
    match: "6S 6 000 mAh · XT90 · 14 min chase",
    why: "Two packs: one on the bird, one charging. 25C is enough for 18 A hover and chase bursts. Sling it under the plate, short leads into the 4-in-1. Ask the vendor to terminate XT90, not XT60.",
    specs: [
      { label: "Pack", value: "6S 6 000 mAh" },
      { label: "Hover", value: "18 A" },
      { label: "Plug", value: "XT90" },
    ],
    buyUrl: "https://www.genstattu.com/",
    vendor: "GensTattu",
    image: "/bom/battery.jpg",
    note: "Photo is the same Tattu 6S family (larger cell count). Order 6000 mAh, 25–35C, XT90.",
  },
  {
    id: "bec-orin",
    catalogId: "battery",
    name: "6S → 19 V buck for Orin",
    sku: "Matek / generic 6–12S to 19 V 5 A",
    brand: "Matek",
    group: "Power",
    tier: "fsd",
    qty: 1,
    unitUsd: 28,
    match: "Orin Super kit barrel is 19 V · must not sag mid-chase",
    why: "The 4-in-1 does not power a Jetson. A dedicated 5 A buck from the 6S rail keeps the detector alive when the pack sags.",
    specs: [
      { label: "In", value: "6S" },
      { label: "Out", value: "19 V 5 A" },
      { label: "Plug", value: "XT60 / barrel 5.5×2.5" },
    ],
    buyUrl: "https://www.mateksys.com/",
    vendor: "Matek / AliExpress",
    image: null,
  },
  {
    id: "bec-5v",
    catalogId: "battery",
    name: "5 V / 12 V UBEC",
    sku: "Matek UBEC Duo 5V/12V",
    brand: "Matek",
    group: "Power",
    tier: "fsd",
    qty: 1,
    unitUsd: 18,
    match: "Gimbal + RX + CSI heater rail",
    why: "Gimbal motors and the 900 MHz RX want a clean 5 V, not the noisy 4-in-1 BEC.",
    specs: [
      { label: "5 V", value: "5 A" },
      { label: "12 V", value: "2 A" },
      { label: "In", value: "3–6S" },
    ],
    buyUrl: "https://www.mateksys.com/",
    vendor: "Matek",
    image: null,
  },
  {
    id: "rx",
    catalogId: "rx",
    name: "900 MHz command receiver",
    sku: "RadioMaster / HappyModel ELRS 900 Nano RX",
    brand: "ExpressLRS",
    group: "Link",
    tier: "fly",
    qty: 1,
    unitUsd: 25,
    match: "900 MHz CRSF · ~8 ms stick · hold / land failsafe",
    why: "CRSF into TELEM2 on the 6C Mini. 900 MHz is the briefing's control band — do not use 2.4 GHz ELRS for the command link if you want the catalog stack.",
    specs: [
      { label: "Control", value: "900 MHz CRSF" },
      { label: "Latency", value: "~8 ms" },
      { label: "Failsafe", value: "Hold / land" },
    ],
    buyUrl: "https://www.radiomasterrc.com/",
    vendor: "RadioMaster",
    image: null,
  },
  {
    id: "tx",
    catalogId: "rx",
    name: "Command radio",
    sku: "RadioMaster TX16S MKII 4-in-1  Mode 2",
    brand: "RadioMaster",
    group: "Link",
    tier: "ground",
    qty: 1,
    unitUsd: 200,
    match: "EdgeTX · module bay for 900 MHz ELRS · full-size gimbals",
    why: "FSD is a setpoint source, not a pilot replacement. A human with a stick is the authority flag. 4-in-1 bay takes the 900 MHz module below.",
    specs: [
      { label: "Firmware", value: "EdgeTX" },
      { label: "Gimbals", value: "Hall V4.0" },
      { label: "Bay", value: "JR / nano" },
    ],
    buyUrl: "https://radiomasterrc.com/blogs/radiomaster-press/radiomaster-radio-comparison-chart",
    vendor: "RadioMaster",
    image: "/bom/radio.jpg",
  },
  {
    id: "txmod",
    catalogId: "rx",
    name: "900 MHz ELRS TX module",
    sku: "RadioMaster Ranger Micro 900  / HappyModel ES900TX",
    brand: "RadioMaster",
    group: "Link",
    tier: "ground",
    qty: 1,
    unitUsd: 45,
    match: "900 MHz CRSF from the TX16S bay",
    why: "Onboard TX16S ELRS is 2.4 GHz. Catalog control is 900 MHz, so the module is required.",
    specs: [
      { label: "Band", value: "900 MHz ISM" },
      { label: "Protocol", value: "CRSF / ELRS" },
      { label: "Fit", value: "Micro bay" },
    ],
    buyUrl: "https://www.radiomasterrc.com/",
    vendor: "RadioMaster",
    image: null,
  },
  {
    id: "telem",
    catalogId: "rx",
    name: "2.4 GHz telemetry pair",
    sku: "Holybro SiK Telemetry Radio V3 2.4 GHz",
    brand: "Holybro",
    group: "Link",
    tier: "ground",
    qty: 1,
    unitUsd: 48,
    match: "2.4 GHz telemetry · QGroundControl",
    why: "Briefing splits control (900 MHz) and telemetry (2.4 GHz). Plug air-side into TELEM1, ground-side into the laptop running QGC.",
    specs: [
      { label: "Band", value: "2.4 GHz" },
      { label: "Stack", value: "SiK / MAVLink" },
      { label: "Pair", value: "Air + ground" },
    ],
    buyUrl: "https://holybro.com/",
    vendor: "Holybro",
    image: null,
  },
  {
    id: "xt90",
    catalogId: "battery",
    name: "XT90 + 12 AWG silicone kit",
    sku: "Amass XT90H · 12 AWG 2 m · heat-shrink",
    brand: "Amass",
    group: "Power",
    tier: "airframe",
    qty: 1,
    unitUsd: 16,
    match: "Short power leads into the 4-in-1",
    why: "Catalog power path is XT90 into the 4-in-1. Pre-tinned 12 AWG, two housings, heat-shrink.",
    specs: [
      { label: "Plug", value: "XT90H" },
      { label: "Wire", value: "12 AWG" },
      { label: "Length", value: "2 m kit" },
    ],
    buyUrl: "https://www.amazon.com/s?k=xt90h+12awg",
    vendor: "Amazon",
    image: null,
  },
  {
    id: "dampen",
    catalogId: "fc",
    name: "FC vibration mount",
    sku: "30.5 / Pixhawk silicone grommet stack",
    brand: "Generic",
    group: "Avionics",
    tier: "fly",
    qty: 1,
    unitUsd: 12,
    match: "Keeps BMI088 off the 10-inch vibration peak",
    why: "A flexing or buzzing stack injects phantom accelerations and ruins camera-to-IMU time sync.",
    specs: [
      { label: "Fit", value: "Pixhawk Mini" },
      { label: "Iso", value: "Silicone" },
    ],
    buyUrl: "https://holybro.com/",
    vendor: "Holybro / Amazon",
    image: null,
  },
  {
    id: "csi",
    catalogId: "camera",
    name: "CSI flex cable",
    sku: "15-pin MIPI CSI 20–30 cm",
    brand: "Arducam",
    group: "Perception",
    tier: "fsd",
    qty: 1,
    unitUsd: 8,
    match: "Gimbal to Orin CSI",
    why: "Stock ribbons are too short once the camera is on the 2-axis. Get a locking 20–30 cm cable.",
    specs: [{ label: "Length", value: "20–30 cm" }],
    buyUrl: "https://www.arducam.com/",
    vendor: "Arducam",
    image: null,
  },
  {
    id: "hardware",
    catalogId: "frame",
    name: "M3 hardware + threadlock",
    sku: "M3×8/10/12 socket · nylock · Loctite 243",
    brand: "Generic",
    group: "Structure",
    tier: "airframe",
    qty: 1,
    unitUsd: 14,
    match: "Arm bolts, motor 19×19, plate standoffs",
    why: "X650 kit includes some hardware. Budget a full M3 pack and blue threadlock for motor screws.",
    specs: [
      { label: "Thread", value: "M3" },
      { label: "Lock", value: "243 blue" },
    ],
    buyUrl: "https://www.amazon.com/s?k=m3+socket+cap+nylock",
    vendor: "Amazon",
    image: null,
  },
  {
    id: "print-cam-mount",
    catalogId: "imu",
    name: "Camera-to-IMU rigid mount",
    sku: "HV-1-CAM-01  ·  REV A",
    brand: "Horizon Vision",
    group: "Avionics",
    tier: "fsd",
    qty: 1,
    unitUsd: 3,
    match: "80 × 36 × 6 mm · 30.5 FC pattern · M2 camera ears",
    why: "This is the camera_link. Print it, do not buy a floppy GoPro mount. A 0.5° flex between the BMI088 and the CSI module is 13 cm of lock error at 15 m. PETG, 6 walls, 40% gyroid.",
    specs: [
      { label: "Envelope", value: "80 × 36 × 6 mm" },
      { label: "Holes", value: "4× M3 + 4× M2" },
      { label: "Mass", value: "11 g" },
    ],
    buyUrl: "",
    vendor: "Print in-house",
    image: null,
    origin: "print",
    cadId: "cam-mount",
    process: "FDM · 0.2 mm · 6 walls",
    materialName: "PETG · 40% gyroid",
    note: "Print two. Keep one as a spare; the ears are the first thing to crack in a tip-over.",
  },
  {
    id: "print-orin-tray",
    catalogId: "npu",
    name: "Orin carrier tray",
    sku: "HV-1-ORIN-02  ·  REV A",
    brand: "Horizon Vision",
    group: "Perception",
    tier: "fsd",
    qty: 1,
    unitUsd: 5,
    match: "90 × 70 × 8 mm · 4 standoff bosses · vent slots",
    why: "The compact carrier is a naked PCB. This tray bolts to the X650 payload holes, holds the module + 2230, and dumps heat through the slots. Do not fly the desktop Dev Kit plate.",
    specs: [
      { label: "Envelope", value: "90 × 70 × 8 mm" },
      { label: "Bosses", value: "M2.5 × 4" },
      { label: "Mass", value: "18 g" },
    ],
    buyUrl: "",
    vendor: "Print in-house",
    image: null,
    origin: "print",
    cadId: "orin-tray",
    process: "FDM · 0.2 mm · 5 walls",
    materialName: "PETG · 35% gyroid",
  },
  {
    id: "print-gimbal-adapter",
    catalogId: "gimbal",
    name: "CSI gimbal adapter",
    sku: "HV-1-GIM-03  ·  REV A",
    brand: "Horizon Vision",
    group: "Perception",
    tier: "fsd",
    qty: 1,
    unitUsd: 2,
    match: "32 × 32 × 3 mm · Ø16 optical · 20 mm M2 square",
    why: "Tarot T-2D expects a GoPro. The AR0234 is a 28 mm CSI board. This adapter is the only interface. Keep the optical axis on the gimbal pitch pivot or the tracker will fight a lever arm.",
    specs: [
      { label: "Envelope", value: "32 × 32 × 3 mm" },
      { label: "Bore", value: "Ø16 mm" },
      { label: "Mass", value: "4 g" },
    ],
    buyUrl: "",
    vendor: "Print in-house",
    image: null,
    origin: "print",
    cadId: "gimbal-adapter",
    process: "FDM · 0.12 mm · 6 walls",
    materialName: "PETG · 100% infill",
  },
  {
    id: "print-batt-tray",
    catalogId: "battery",
    name: "Under-plate battery tray",
    sku: "HV-1-BATT-06  ·  REV A",
    brand: "Horizon Vision",
    group: "Power",
    tier: "airframe",
    qty: 1,
    unitUsd: 4,
    match: "155 × 50 × 10 mm · strap slots · XT90 pass",
    why: "Keeps the 6S 6000 on the CG and stops it walking into a prop. Two 20 mm strap slots, XT90 window on the nose side. Print in PETG, not PLA — bench heat plus a sagging pack will warp PLA.",
    specs: [
      { label: "Envelope", value: "155 × 50 × 10 mm" },
      { label: "Straps", value: "20 mm × 2" },
      { label: "Mass", value: "22 g" },
    ],
    buyUrl: "",
    vendor: "Print in-house",
    image: null,
    origin: "print",
    cadId: "batt-tray",
    process: "FDM · 0.24 mm · 4 walls",
    materialName: "PETG · 30% gyroid",
  },
  {
    id: "print-ant-clip",
    catalogId: "rx",
    name: "900 MHz antenna clip",
    sku: "HV-1-ANT-05  ·  REV A",
    brand: "Horizon Vision",
    group: "Link",
    tier: "fly",
    qty: 2,
    unitUsd: 1,
    match: "Clips onto 20 mm carbon arm · Ø4 dipole seat",
    why: "Keeps the ELRS dipole off the carbon and out of the motor bell. Print two, one per rear arm, opposite polarisation.",
    specs: [
      { label: "Tube", value: "Ø20 mm snap" },
      { label: "Seat", value: "Ø4 mm" },
      { label: "Mass", value: "2 g ea" },
    ],
    buyUrl: "",
    vendor: "Print in-house",
    image: null,
    origin: "print",
    cadId: "ant-clip",
    process: "FDM · 0.16 mm · 4 walls",
    materialName: "PETG · 100% infill",
  },
  {
    id: "print-gps-collar",
    catalogId: "gps",
    name: "GPS mast isolation collar",
    sku: "HV-1-GPS-04  ·  REV A",
    brand: "Horizon Vision",
    group: "Navigation",
    tier: "fly",
    qty: 1,
    unitUsd: 1,
    match: "Ø18 × 12 mm TPU · 8 mm mast bore",
    why: "TPU collar between the F9P mast and the carbon plate. Kills the 10-inch vibration peak that otherwise walks the mag.",
    specs: [
      { label: "OD", value: "Ø18 mm" },
      { label: "Bore", value: "Ø8 mm" },
      { label: "Mass", value: "3 g" },
    ],
    buyUrl: "",
    vendor: "Print in-house",
    image: null,
    origin: "print",
    cadId: "gps-collar",
    process: "FDM · 0.16 mm · 3 walls",
    materialName: "TPU 95A · 20% infill",
  },
  {
    id: "print-csi-clamp",
    catalogId: "camera",
    name: "CSI strain relief",
    sku: "HV-1-CSI-07  ·  REV A",
    brand: "Horizon Vision",
    group: "Perception",
    tier: "fsd",
    qty: 1,
    unitUsd: 1,
    match: "U-clamp on gimbal yaw · 15-pin ribbon",
    why: "The CSI flex is the first thing to tear when the gimbal yaws to the stop. This TPU clamp takes the bend, not the connector.",
    specs: [
      { label: "Ribbon", value: "15-pin · 1 mm" },
      { label: "Clamp", value: "12 × 8 × 6 mm" },
      { label: "Mass", value: "1 g" },
    ],
    buyUrl: "",
    vendor: "Print in-house",
    image: null,
    origin: "print",
    cadId: "csi-clamp",
    process: "FDM · 0.12 mm · 3 walls",
    materialName: "TPU 95A · 100% infill",
  },
  {
    id: "print-landing-feet",
    catalogId: "frame",
    name: "TPU landing feet",
    sku: "HV-1-LG-08  ·  REV A",
    brand: "Horizon Vision",
    group: "Structure",
    tier: "airframe",
    qty: 4,
    unitUsd: 1,
    match: "22 × 22 × 12 mm pads · X650 tube ends",
    why: "Stock X650 feet are hard nylon. TPU pads keep Dubai grit out of the 3115 bells and take the last 10 cm of a firm landing.",
    specs: [
      { label: "Pad", value: "22 × 22 mm" },
      { label: "Height", value: "12 mm" },
      { label: "Mass", value: "4 g ea" },
    ],
    buyUrl: "",
    vendor: "Print in-house",
    image: null,
    origin: "print",
    cadId: "landing-foot",
    process: "FDM · 0.2 mm · 3 walls",
    materialName: "TPU 95A · 15% infill",
  },
  {
    id: "charger",
    catalogId: null,
    name: "6S AC charger",
    sku: "ISDT 608AC  250 W",
    brand: "ISDT",
    group: "Ground",
    tier: "ground",
    qty: 1,
    unitUsd: 89,
    match: "6S LiPo · balance · 240 V UAE mains",
    why: "You cannot fly two packs without a charger that does 6S on wall power. 608AC is 100–240 V.",
    specs: [
      { label: "Power", value: "250 W AC" },
      { label: "Cells", value: "1–6S" },
      { label: "Mains", value: "100–240 V" },
    ],
    buyUrl: "https://www.isdt.co/",
    vendor: "ISDT",
    image: null,
  },
  {
    id: "bag",
    catalogId: null,
    name: "LiPo fire bag",
    sku: "Large LiPo safe bag  (2× 6000 6S)",
    brand: "Generic",
    group: "Ground",
    tier: "ground",
    qty: 1,
    unitUsd: 18,
    match: "Charge and store both packs",
    why: "Charge only in the bag, never unattended on a workbench.",
    specs: [{ label: "Fit", value: "2× 6S 6000" }],
    buyUrl: "https://www.amazon.com/s?k=lipo+safe+bag+large",
    vendor: "Amazon",
    image: null,
  },
  {
    id: "tools",
    catalogId: null,
    name: "Hex + prop tool",
    sku: "1.5 / 2 / 2.5 / 3 mm hex · M5 prop wrench · snips",
    brand: "Wiha / generic",
    group: "Ground",
    tier: "ground",
    qty: 1,
    unitUsd: 24,
    match: "Motor M3, frame, M5 prop nuts",
    why: "X650 includes a starter hex. A proper ball-hex set and a dedicated M5 prop wrench pay for themselves on the first motor swap.",
    specs: [{ label: "Hex", value: "1.5–3 mm" }],
    buyUrl: "https://www.amazon.com/s?k=hex+driver+set+rc",
    vendor: "Amazon",
    image: null,
  },
  {
    id: "pad",
    catalogId: null,
    name: "Landing pad",
    sku: "90 cm folding pad",
    brand: "Generic",
    group: "Ground",
    tier: "ground",
    qty: 1,
    unitUsd: 32,
    match: "Keeps sand out of 10-inch props in Dubai",
    why: "Desert dust in the bells will kill 3115 bearings. A pad is cheaper than a motor.",
    specs: [{ label: "Size", value: "90 cm" }],
    buyUrl: "https://www.amazon.com/s?k=drone+landing+pad+90cm",
    vendor: "Amazon",
    image: null,
  },
  {
    id: "spares-props",
    catalogId: "props",
    name: "Spare carbon props",
    sku: "HQProp 10×5.5×2 CF  (second 2-pair)",
    brand: "HQProp",
    group: "Ground",
    tier: "ground",
    qty: 2,
    unitUsd: 18,
    match: "Same 10×5.5 pairing",
    why: "10-inch carbon does not survive a tip strike. Fly with a spare pair in the bag.",
    specs: [
      { label: "Size", value: "10 × 5.5 × 2" },
      { label: "Pairing", value: "2 CW + 2 CCW" },
    ],
    buyUrl: "https://www.hqprop.com/",
    vendor: "HQProp",
    image: "/bom/props.jpg",
  },
  {
    id: "spare-motor",
    catalogId: "motors",
    name: "Spare 3115 900 Kv",
    sku: "Hobbywing XRotor 3115 900KV",
    brand: "Hobbywing",
    group: "Ground",
    tier: "ground",
    qty: 1,
    unitUsd: 36,
    match: "One bell in the spares tin",
    why: "A single dead motor grounds the article. Keep one matching winding on the shelf.",
    specs: [
      { label: "Kv", value: "900" },
      { label: "Stator", value: "31 × 15 mm" },
    ],
    buyUrl: "https://www.hobbywing.com/en/products/xrotor3115",
    vendor: "Hobbywing",
    image: "/bom/motor.jpg",
  },
];

export function originOf(item: BomItem): Origin {
  if (item.included) return "included";
  return item.origin ?? "buy";
}

export function lineTotal(item: BomItem) {
  if (item.included) return 0;
  return item.qty * item.unitUsd;
}

export function kitTotal(items: BomItem[]) {
  return items.reduce((s, it) => s + lineTotal(it), 0);
}

export function itemsForPart(partId: string) {
  return ITEMS.filter((it) => it.id === partId || it.catalogId === partId);
}

export type KitLabel = {
  title: string;
  sku: string;
  brand: string;
  group: string;
};

export function primaryItemForPart(partId: string): BomItem | undefined {
  const items = itemsForPart(partId);
  const exact = items.find((i) => i.id === partId);
  if (exact) return exact;
  const fly = items.filter((i) => i.tier !== "ground");
  const pool = fly.length ? fly : items;
  return (
    pool.find((i) => originOf(i) === "buy") ??
    pool.find((i) => originOf(i) === "included") ??
    pool[0]
  );
}

export function kitLabel(partId: string): KitLabel {
  const item = primaryItemForPart(partId);
  if (!item) {
    return { title: partId, sku: "", brand: "", group: "" };
  }
  return {
    title: item.name,
    sku: item.sku,
    brand: item.brand,
    group: item.group,
  };
}

export const ASSEMBLY_BALLOONS: { n: number; id: string; call: string }[] = [
  { n: 1, id: "frame", call: "HV-1-FRM-00 chassis" },
  { n: 2, id: "motors", call: "XRotor 3115 900Kv" },
  { n: 3, id: "props", call: "HQProp 10×5.5×2 CF" },
  { n: 4, id: "escs", call: "XRotor 45A 4-in-1" },
  { n: 5, id: "fc", call: "Pixhawk 6C Mini" },
  { n: 6, id: "imu", call: "BMI088 (on 6C)" },
  { n: 7, id: "npu", call: "Orin Nano 8 GB" },
  { n: 8, id: "camera", call: "Arducam AR0234" },
  { n: 9, id: "gimbal", call: "Tarot T-2D" },
  { n: 10, id: "gps", call: "H-RTK NEO-F9P" },
  { n: 11, id: "mag", call: "RM3100" },
  { n: 12, id: "battery", call: "Tattu 6S 6000" },
  { n: 13, id: "rx", call: "ELRS 900 Nano" },
];

export const CORE_TOTAL = kitTotal(ITEMS.filter((i) => i.tier !== "ground"));
export const FULL_TOTAL = kitTotal(ITEMS);
export const ITEM_COUNT = ITEMS.filter((i) => !i.included).length;
export const PRINT_ITEMS = ITEMS.filter((i) => originOf(i) === "print");

function csvCell(value: string | number) {
  const t = String(value);
  if (/[",\n]/.test(t)) return `"${t.replace(/"/g, '""')}"`;
  return t;
}

export function kitCsv(items: BomItem[] = ITEMS) {
  const header = [
    "group",
    "name",
    "sku",
    "brand",
    "origin",
    "qty",
    "unit_usd",
    "line_usd",
    "vendor",
    "url",
    "process",
    "material",
    "tier",
  ];
  const rows = items.map((i) =>
    [
      i.group,
      i.name,
      i.sku,
      i.brand,
      originOf(i),
      i.qty,
      i.included ? 0 : i.unitUsd,
      lineTotal(i),
      i.vendor,
      i.buyUrl,
      i.process ?? "",
      i.materialName ?? "",
      i.tier,
    ]
      .map(csvCell)
      .join(","),
  );
  return [header.join(","), ...rows].join("\n");
}
